Repository openebs/velero-plugin, pull requests merged in 2020-09, with the labels that each got.

#110 chore(refactor): making directory and binary name openebs specific
  changelogs/unreleased/110-pawanpraka1
  velero-blockstore-openebs/main.go
Labels: Enhancement

#102 feat(velero): velero plugin for backup and restore for ZFS-LocalPV
  Makefile
  changelogs/unreleased/102-pawanpraka1
  go.mod
  go.sum
  pkg/zfs/plugin/backup.go
  pkg/zfs/plugin/restore.go
  pkg/zfs/plugin/zfs.go
  pkg/zfs/snapshot/snap.go
  pkg/zfs/utils/utils.go
  velero-blockstore-openebs/main.go
Labels: Enhancement

#111 feat(velero): adding support for parallel backup and restore
  changelogs/unreleased/111-pawanpraka1
  pkg/clouduploader/operation.go
  pkg/clouduploader/server.go
  pkg/cstor/api_service.go
  pkg/cstor/cstor.go
  pkg/cstor/pv_operation.go
  pkg/zfs/plugin/backup.go
  pkg/zfs/plugin/restore.go
  pkg/zfs/plugin/zfs.go
  pkg/zfs/utils/utils.go
Labels: Enhancement

#114 docs(changelog): changelog for v2.1.0
  CHANGELOG.md
  changelogs/released/v2.1.0/102-pawanpraka1
  changelogs/released/v2.1.0/108-mittachaitu
  changelogs/released/v2.1.0/110-pawanpraka1
  changelogs/released/v2.1.0/111-pawanpraka1
Labels: Documentation

#116 feat(log): making log level available for velero plugin
  changelogs/116-pawanpraka1
  go.mod
  velero-blockstore-openebs/main.go
Labels: Enhancement

#117 feat(velero): wait for plugin server to be UP before doing backup/restore
  changelogs/unreleased/116-pawanpraka1
  changelogs/unreleased/117-pawanpraka1
  go.mod
  go.sum
  pkg/clouduploader/conn.go
  pkg/clouduploader/operation.go
  pkg/clouduploader/server.go
  pkg/zfs/plugin/backup.go
  pkg/zfs/plugin/restore.go
  pkg/zfs/plugin/zfs.go
Labels: Enhancement

#118 feat(zfspv): adding support to restore on different setup/nodes
  changelogs/unreleased/118-pawanpraka1
  pkg/velero/restore.go
  pkg/zfs/plugin/restore.go
  pkg/zfs/plugin/zfs.go
Labels: feature

#115 feat(s3): support to use custom certificate for s3 object storage
  changelogs/unreleased/115-mynktl
  example/06-volumesnapshotlocation.yaml
  pkg/clouduploader/conn.go
Labels: Enhancement
