Repository openebs/velero-plugin, pull requests merged in 2020-08, with the labels that each got.

#101 fix(build): use buildscript file `push` from openebs/chart
  .gitignore
  Makefile
  push
Labels: Maintenance

#103 chore(linters): enabling few linters for local and travis build
  .golangci.yml
  Makefile
Labels: Maintenance

#106 docs(changelog): Adding changelog for v2.0.0
  CHANGELOG.md
Labels: Documentation

#108 fix(csi, local restore): add support for local restore of cStor CSI volume
  changelogs/unreleased/108-mittachaitu
  pkg/cstor/api_service.go
  pkg/cstor/cstor.go
  pkg/cstor/pv_operation.go
Labels: Bug
