Repository openebs/velero-plugin, pull requests merged in 2020-10, with the labels that each got.

#121 feat(zfspv): adding support to do incremental backup/restore
  changelogs/unreleased/121-pawanpraka1
  pkg/clouduploader/operation.go
  pkg/zfs/plugin/backup.go
  pkg/zfs/plugin/restore.go
  pkg/zfs/plugin/zfs.go
  pkg/zfs/utils/utils.go
Labels: feature

#130 docs(changelog): Adding changelog for release v2.2.0
  CHANGELOG.md
  changelogs/released/v2.2.0-RC1/115-mynktl
  changelogs/released/v2.2.0-RC1/116-pawanpraka1
  changelogs/released/v2.2.0-RC1/117-pawanpraka1
  changelogs/released/v2.2.0-RC1/118-pawanpraka1
  changelogs/released/v2.2.0-RC1/121-pawanpraka1
  changelogs/released/v2.2.0-RC2/124-pawanpraka1
  changelogs/released/v2.2.0-RC2/128-pawanpraka1
Labels: Documentation

#99 feat(restore): Optimizing restore for incremental backup
  README.md
  changelogs/unreleased/99-mynktl
  example/06-volumesnapshotlocation.yaml
  pkg/clouduploader/operation.go
  pkg/cstor/cstor.go
  pkg/cstor/pv_operation.go
  script/volumesnapshotlocation.yaml
  tests/sanity/backup_test.go
  tests/velero/restore.go
Labels: Enhancement
